[package]
name = "powerbank"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rtt-target = "0.4.0"

cortex-m = {version = "^0.7.7", features = ["critical-section-single-core"]}
cortex-m-rt = "0.7.3"

# Change this import as required for your MCU.
# stm32-hal2 = { version = "^1.5.5", features = ["f405", "f4rt"]}

# panic-halt = "0.2.0"
defmt-rtt = "0.4.0"
critical-section = "1.1.2"
panic-rtt-target = { version = "0.1.2", features = ["cortex-m"]}
mipidsi = "0.7.1"

display-interface-spi = "0.4.1"
embedded-graphics = "0.8.1"
embedded-hal = { version = "0.2.7", features = ["unproven"] }
# st7789 = "0.7.0"
# ina3221 = "0.4.5"
ina3221 = { git = "https://github.com/kiranshila/INA3221.git" }
# bq40z50 = "0.1.4"
st7789v = { git = "https://github.com/wose/st7789v.git" }
byteorder = { version = "1.5.0", default-features = false }
arrform = "0.1.1"

[dependencies.stm32f1xx-hal]
version = "0.10.0"
features = ["rt", "stm32f103", "medium"]
